### ISSUE TITLE
[Feature Request] NavigateFrom method

### ISSUE THREAD

**Issue by jzeferino** [jamesmontemagno/LaunchMapsPlugin#1]
@jamesmontemagno I will need to implement a similar method like NavigateTo.
But I want to Navigate from my current position to end position.
Example:

```
Task<bool> NavigateTo(string originName, double originLatitude, double originLongitude, string destinationName, double destinationLatitude, double destinationLongitude, NavigationType navigationType = NavigationType.Default);
```

Maybe its better to create a Class to aggregate the name, latitude and longitude.

Can i make a PR after i implement that? (Will do it for Android and iOS)

**Comment by jamesmontemagno** [comment]
Essentially you want a NavigateFrom method. You could add these in there and need to implement on all platforms. We can collaborate on it though if you start a new branch and send a PR down.

**Comment by jzeferino** [comment]
Yes. I will try to PR that after I implement it for iOS and Android. (Will implement that next week).

**Comment by jzeferino** [comment]
After some reflection, what i really need was the NavigateTo. I just wanted to navigate from my current location to a end location. And this method does that. 
I was wrong.
