### ISSUE TITLE
iOS: Navigate to street

### ISSUE THREAD

**Issue by c-lamont** [jamesmontemagno/LaunchMapsPlugin#10]
I only have the postcode of an address and I want to navigate to it. 
On Android this works fine by setting the street as the postcode. 
On iOS when I set only the street name, it does not open the map at all.

## Bug Information

Version Number of Plugin: 4.0.1
Device Tested On: Samsung S6
Simulator Tested On: iPhone 8 iOS 11.1
Version of VS: 
Version of Xamarin: 7.2.2
Versions of other things you are using:

### Steps to reproduce the Behavior
On iOS, navigate to an address and set only its street name.

### Expected Behavior
The map opens at the street name.

### Actual Behavior
The map does not open at all.

**Comment by jamesmontemagno** [comment]
On iOS I have to give it lat/long to open up, so i do a geocode lookup: https://github.com/jamesmontemagno/LaunchMapsPlugin/blob/master/src/ExternalMaps.Plugin.iOS/ExternalMapsImplementation.cs#L102

Have you tried filling in the country code?

**Comment by c-lamont** [comment]
I am not sure what the country code will be as I only have a postcode. Some postcodes do however open the map so I think it might be something to do with where the phone is currently located.
