### ISSUE TITLE
A way to clear favorites from Apple maps ?

### ISSUE THREAD

**Issue by stephenhauck** [jamesmontemagno/LaunchMapsPlugin#12]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: Current
Device Tested On: iPad, current OS
Simulator Tested On: iPadAir 2 - 11.2
Version of VS: Current (VS 2017)
Version of Xamarin: Current
Versions of other things you are using:

The plugin work great.
My users are setting "favorites" on their devices .....
Is there a way to add and or clear the favorites in code ?

**Comment by jamesmontemagno** [comment]
Not that I know of as this library doesn't do that. You may want to ask in forums.
