### ISSUE TITLE
Waze

### ISSUE THREAD

**Issue by Osmosis311** [jamesmontemagno/LaunchMapsPlugin#15]
Any way to add an option for Waze?

Thanks!

**Comment by gabrweu** [comment]
Sorry if I missed it, but is there any news on supporting Waze? Or rather, having the option to open the dialog asking what map app to use for Android even if Google Maps is found.

**Comment by jamesmontemagno** [comment]
how the implementation works today here is that it will try to open google maps, if not installed then falls back to normal intent system.

If you want it to always be generic prompt I would suggest transitioning to Xamarin.Essentials: https://docs.microsoft.com/en-us/xamarin/essentials/maps

I am no longer adding features as Essentials is the evolution of this plugin.
