### ISSUE TITLE
iOS support ability to launch Google Maps?

### ISSUE THREAD

**Issue by jennablackwell** [jamesmontemagno/LaunchMapsPlugin#16]
Currently, if you only have Google Maps installed, it will ask you to restore Apple Maps.  It would be nice to have the option or ability to have it also launch Google Maps or use whatever other map app is installed.  We have project requirements to have this ability because Apple Maps is not seen as reliable.

**Comment by jamesmontemagno** [comment]
You will need to launch them via URL scheme: https://developers.google.com/maps/documentation/ios-sdk/urlscheme
