### ISSUE TITLE
Multipl Pins on Map

### ISSUE THREAD

**Issue by mick1313** [jamesmontemagno/LaunchMapsPlugin#2]
Is there an easy way to drop a few pins on the map... and mark current location with your plugin?  Basically we want to list nearby hospitals....  the user can select one and get directions from the mapping application.. .but we need to pass in a few Lat/Long type coords.

**Comment by jamesmontemagno** [comment]
Take a look at https://github.com/jamesmontemagno/Coffee-Filter as it does this for coffee and does navigation too.
