### ISSUE TITLE
Turn off panel at bottom iOS or use Google on iOS ?

### ISSUE THREAD

**Issue by stephenhauck** [jamesmontemagno/LaunchMapsPlugin#4]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Feature request

Version Number of Plugin: Current
Device Tested On:  n / a 
Simulator Tested On: 6S Plus iOS 10
## Feature Request:

Can we turn off the panel at the bottom somehow (See attached image)?
Can I choose to call Google Maps on iOS somehow?
<img width="628" alt="map" src="https://cloud.githubusercontent.com/assets/12648793/19492822/51705ef8-9546-11e6-89bf-871cc4ac419a.png">

**Comment by jamesmontemagno** [comment]
It is there by default, no control once I launch app
