### ISSUE TITLE
Feature request: Specify both source and destination locations

### ISSUE THREAD

**Issue by hardcodet** [jamesmontemagno/LaunchMapsPlugin#9]
## Feature Request:

The plugin currently allows us to specify only one location - at least for Google Maps (I think), it would be possible to specify a start address, too, which would enable us to open the app showing directions from a given location to a given destination.

**Comment by taylanken** [comment]
I'd like to give this a try

**Comment by jamesmontemagno** [comment]
Moving all feature requests to https://github.com/xamarin/Essentials as that is the replacement for this and already improves it vastly.
